_partial_: true
_target_: controllable_patching_striding.models.decoders.vstride_decoder.VstrideDecoder
learned_pad: true
base_kernel_size1d:
  - [4, 4]
base_kernel_size2d: 
  - [8, 4]
  - [8, 4]
base_kernel_size3d: 
  - [4, 4]
  - [4, 4]
  - [4, 4] # Assume this is for all dimensions unless a tuple is passed
groups: 12